name: Lint
on: [pull_request]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint changelog
        uses: avto-dev/markdown-lint@v1
        with:
          rules: "/lint/rules/changelog.js"
          config: "/lint/config/changelog.yml"
          args: "CHANGELOG.md"
      - uses: ricardochaves/python-lint@v1.4.0
        with:
          use-pylint: false
          use-pycodestyle: false
          use-flake8: true
          use-black: true
          use-mypy: false
          use-isort: true
